# Generated by Django 2.1.3 on 2019-11-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20191112_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=models.CharField(blank=True, help_text='如果设置的不是HTML类型，可为空', max_length=500, verbose_name='内容'),
        ),
    ]
